### ISSUE TITLE
[FR]: Publish to Bazel Central Registry (bzlmod)

### ISSUE THREAD

**Issue by alexeagle** [aspect-build/rules_cypress#34]
### Describe the feature

Make Cypress testing available to bzlmod users with nothing in WORKSPACE

**Comment by jestapinski** [comment]
👋  Any update here?

**Comment by alexeagle** [comment]
Hey, sorry we haven't had time to get this one to 1.0 yet. Contributions welcome (fiscal or PRs)

**Comment by betaboon** [comment]
Hello,

I saw https://github.com/aspect-build/rules_cypress/pull/69 and https://github.com/aspect-build/rules_cypress/pull/71 have been merged.

does this mean we're close or already there?

what's missing and how can i help ? :)

cc @gregmagolan
